swagger: "2.0"
info:
  version: "0.0.1"
  title: Usergrid Objects Example
host: localhost
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - application/octet-stream
  - application/x-www-form-urlencoded
produces:
  - application/json
x-a127-config: {}
x-volos-resources: {}
paths:
  /dogs:
    x-swagger-router-controller: dogs
    get:
      operationId: list
      responses:
        default:
          description: "Default"
          schema:
            $ref: "GenericResponse"
    post:
      operationId: create
      responses:
        default:
          description: "Default"
          schema:
            $ref: "GenericResponse"
  /dogs/{id}:
    x-swagger-router-controller: dogs
    parameters:
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: delete
      responses:
        default:
          description: "Default"
          schema:
            $ref: "GenericResponse"
    get:
      operationId: get
      responses:
        default:
          description: "Default"
          schema:
            $ref: "GenericResponse"
    put:
      operationId: update
      responses:
        default:
          description: "Default"
          schema:
            $ref: "GenericResponse"
  /dogs/{id}/pet:
    x-swagger-router-controller: dogs
    parameters:
      - name: id
        in: path
        required: true
        type: string
    post:
      operationId: pet
      responses:
        default:
          description: "Default"
          schema:
            $ref: "GenericResponse"
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GenericResponse:
    required: []
